// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiw0ekvvVUfToc37QZ4VtzkeF8ir2Tgs',
    appId: '1:4907483683:web:c4c2c93d0fa6db58992796',
    messagingSenderId: '4907483683',
    projectId: 'weconnectdb-383ad',
    authDomain: 'weconnectdb-383ad.firebaseapp.com',
    storageBucket: 'weconnectdb-383ad.appspot.com',
    measurementId: 'G-6X60W12GV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrDNGIsw6_c4GhTof6rqvn2RPREcwZ5fg',
    appId: '1:4907483683:android:d4f8e30d675be6dd992796',
    messagingSenderId: '4907483683',
    projectId: 'weconnectdb-383ad',
    storageBucket: 'weconnectdb-383ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOMbIyIEgMsub8rWOACqoB79bGyDN44rE',
    appId: '1:4907483683:ios:f72c64ca913d14da992796',
    messagingSenderId: '4907483683',
    projectId: 'weconnectdb-383ad',
    storageBucket: 'weconnectdb-383ad.appspot.com',
    iosBundleId: 'com.example.weconnect',
  );
}
